version : '3.8'

services:
    # redis:
        # image: redis
        # ports:
        #     - 6379:6379
    app:
        build:
            context: ./docker
            dockerfile: app.dockerfile
        ports:
            - 8001:80
        volumes:
            - ./html:/var/www/html


    database:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 33061:3306
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

    # mongo:
    #     image: mongo
    #     restart: always
    #     environment:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: example
    
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes:
    dbdata: